### PR TITLE
Update DisplayLink Manager download link

### LINKED ISSUE #51: DisplayLink Manager URL change
Looks like Synaptics updated their site. The Manager download link is no longer the Drupal-style `node/n` but e.g., currently: `https://www.synaptics.com/products/displaylink-graphics/downloads/macos-connectivity-1.10.2?filetype=exe`. Might actually make the regex simpler. I'll see if I have time to test.

### PR DESCRIPTION
**Pull request by smaddock**
Fixed #51

### CODE REVIEW

**Comment by nstrauss** [comment]
Came here when I found the recipe failing. Thanks @smaddock!

**Comment by jby** [comment]
I was about to post the exact same comment as @nstrauss - but it seems unnecessary...

**Comment by macmule** [comment]
me +3 :)

**Comment by MLBZ521** [comment]
The regex pattern could actually be simplified further to:
```yaml
re_pattern: /%SEARCH_URL%.+\?filetype=exe
```

**Comment by smaddock** [comment]
Not sure how I missed that, will update.

**Comment by Daz-wallace** [comment]
me +4 :D

**Comment by kinglok** [comment]
Me +5 ^_^

**Pull request merged**
